services:
  - type: web
    name: energymind-api
    runtime: docker
    repo: https://github.com/danacioDS/energy_mind
    plan: free
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
